using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ZaferTurizm.Domain;

namespace ZaferTurizm.DataAccess.SeedData
{
    internal class CityData
    {
        public readonly static Province Data01_Adana = new Province() { Id = 1, Name = "Adana" };
        public readonly static Province Data02_Adıyaman = new Province() { Id = 2, Name = "Adıyaman" };
        public readonly static Province Data03_Afyon = new Province() { Id = 3, Name = "Afyon" };
        public readonly static Province Data04_Ağrı = new Province() { Id = 4, Name = "Ağrı" };
        public readonly static Province Data05_Aksaray = new Province() { Id = 5, Name = "Aksaray" };
        public readonly static Province Data06_Amasya = new Province() { Id = 6, Name = "Amasya" };
        public readonly static Province Data07_Ankara = new Province() { Id = 7, Name = "Ankara" };
        public readonly static Province Data08_Antalya = new Province() { Id = 8, Name = "Antalya" };
        public readonly static Province Data09_Ardahan = new Province() { Id = 9, Name = "Ardahan" };
        public readonly static Province Data10_Artvin = new Province() { Id = 10, Name = "Artvin" };
        public readonly static Province Data11_Aydın = new Province() { Id = 11, Name = "Aydın" };
        public readonly static Province Data12_Balıkesir = new Province() { Id = 12, Name = "Balıkesir" };
        public readonly static Province Data13_Bartın = new Province() { Id = 13, Name = "Bartın" };
        public readonly static Province Data14_Batman = new Province() { Id = 14, Name = "Batman" };
        public readonly static Province Data15_Bayburt = new Province() { Id = 15, Name = "Bayburt" };
        public readonly static Province Data16_Bilecik = new Province() { Id = 16, Name = "Bilecik" };
        public readonly static Province Data17_Bingöl = new Province() { Id = 17, Name = "Bingöl" };
        public readonly static Province Data18_Bitlis = new Province() { Id = 18, Name = "Bitlis" };
        public readonly static Province Data19_Bolu = new Province() { Id = 19, Name = "Bolu" };
        public readonly static Province Data20_Burdur = new Province() { Id = 20, Name = "Burdur" };
        public readonly static Province Data21_Bursa = new Province() { Id = 21, Name = "Bursa" };
        public readonly static Province Data22_Çanakkale = new Province() { Id = 22, Name = "Çanakkale" };
        public readonly static Province Data23_Çankırı = new Province() { Id = 23, Name = "Çankırı" };
        public readonly static Province Data24_Çorum = new Province() { Id = 24, Name = "Çorum" };
        public readonly static Province Data25_Denizli = new Province() { Id = 25, Name = "Denizli" };
        public readonly static Province Data26_Diyarbakır = new Province() { Id = 26, Name = "Diyarbakır" };
        public readonly static Province Data27_Düzce = new Province() { Id = 27, Name = "Düzce" };
        public readonly static Province Data28_Edirne = new Province() { Id = 28, Name = "Edirne" };
        public readonly static Province Data29_Elazığ = new Province() { Id = 29, Name = "Elazığ" };
        public readonly static Province Data30_Erzincan = new Province() { Id = 30, Name = "Erzincan" };
        public readonly static Province Data31_Erzurum = new Province() { Id = 31, Name = "Erzurum" };
        public readonly static Province Data32_Eskişehir = new Province() { Id = 32, Name = "Eskişehir" };
        public readonly static Province Data33_Gaziantep = new Province() { Id = 33, Name = "Gaziantep" };
        public readonly static Province Data34_Giresun = new Province() { Id = 34, Name = "Giresun" };
        public readonly static Province Data35_Gümüşhane = new Province() { Id = 35, Name = "Gümüşhane" };
        public readonly static Province Data36_Hakkari = new Province() { Id = 36, Name = "Hakkari" };
        public readonly static Province Data37_Hatay = new Province() { Id = 37, Name = "Hatay" };
        public readonly static Province Data38_Iğdır = new Province() { Id = 38, Name = "Iğdır" };
        public readonly static Province Data39_Isparta = new Province() { Id = 39, Name = "Isparta" };
        public readonly static Province Data40_İstanbul = new Province() { Id = 40, Name = "İstanbul" };
        public readonly static Province Data41_İzmir = new Province() { Id = 41, Name = "İzmir" };
        public readonly static Province Data42_Kahramanmaraş = new Province() { Id = 42, Name = "Kahramanmaraş" };
        public readonly static Province Data43_Karabük = new Province() { Id = 43, Name = "Karabük" };
        public readonly static Province Data44_Karaman = new Province() { Id = 44, Name = "Karaman" };
        public readonly static Province Data45_Kars = new Province() { Id = 45, Name = "Kars" };
        public readonly static Province Data46_Kastamonu = new Province() { Id = 46, Name = "Kastamonu" };
        public readonly static Province Data47_Kayseri = new Province() { Id = 47, Name = "Kayseri" };
        public readonly static Province Data48_Kırıkkale = new Province() { Id = 48, Name = "Kırıkkale" };
        public readonly static Province Data49_Kırklareli = new Province() { Id = 49, Name = "Kırklareli" };
        public readonly static Province Data50_Kırşehir = new Province() { Id = 50, Name = "Kırşehir" };
        public readonly static Province Data51_Kilis = new Province() { Id = 51, Name = "Kilis" };
        public readonly static Province Data52_Kocaeli = new Province() { Id = 52, Name = "Kocaeli" };
        public readonly static Province Data53_Konya = new Province() { Id = 53, Name = "Konya" };
        public readonly static Province Data54_Kütahya = new Province() { Id = 54, Name = "Kütahya" };
        public readonly static Province Data55_Malatya = new Province() { Id = 55, Name = "Malatya" };
        public readonly static Province Data56_Manisa = new Province() { Id = 56, Name = "Manisa" };
        public readonly static Province Data57_Mardin = new Province() { Id = 57, Name = "Mardin" };
        public readonly static Province Data58_Mersin = new Province() { Id = 58, Name = "Mersin" };
        public readonly static Province Data59_Muğla = new Province() { Id = 59, Name = "Muğla" };
        public readonly static Province Data60_Muş = new Province() { Id = 60, Name = "Muş" };
        public readonly static Province Data61_Nevşehir = new Province() { Id = 61, Name = "Nevşehir" };
        public readonly static Province Data62_Niğde = new Province() { Id = 62, Name = "Niğde" };
        public readonly static Province Data63_Ordu = new Province() { Id = 63, Name = "Ordu" };
        public readonly static Province Data64_Osmaniye = new Province() { Id = 64, Name = "Osmaniye" };
        public readonly static Province Data65_Rize = new Province() { Id = 65, Name = "Rize" };
        public readonly static Province Data66_Sakarya = new Province() { Id = 66, Name = "Sakarya" };
        public readonly static Province Data67_Samsun = new Province() { Id = 67, Name = "Samsun" };
        public readonly static Province Data68_Siirt = new Province() { Id = 68, Name = "Siirt" };
        public readonly static Province Data69_Sinop = new Province() { Id = 69, Name = "Sinop" };
        public readonly static Province Data70_Sivas = new Province() { Id = 70, Name = "Sivas" };
        public readonly static Province Data71_Şanlıurfa = new Province() { Id = 71, Name = "Şanlıurfa" };
        public readonly static Province Data72_Şırnak = new Province() { Id = 72, Name = "Şırnak" };
        public readonly static Province Data73_Tekirdağ = new Province() { Id = 73, Name = "Tekirdağ" };
        public readonly static Province Data74_Tokat = new Province() { Id = 74, Name = "Tokat" };
        public readonly static Province Data75_Trabzon = new Province() { Id = 75, Name = "Trabzon" };
        public readonly static Province Data76_Tunceli = new Province() { Id = 76, Name = "Tunceli" };
        public readonly static Province Data77_Uşak = new Province() { Id = 77, Name = "Uşak" };
        public readonly static Province Data78_Van = new Province() { Id = 78, Name = "Van" };
        public readonly static Province Data79_Yalova = new Province() { Id = 79, Name = "Yalova" };
        public readonly static Province Data80_Yozgat = new Province() { Id = 80, Name = "Yozgat" };
        public readonly static Province Data81_Zonguldak = new Province() { Id = 81, Name = "Zonguldak" };
    }
}
